### ISSUE TITLE
Stable Diffusion Implementation?

### ISSUE THREAD

**Issue by MiLO83** [BrianPeek/ZMachineLib#1]
Hi,
You work for Microsoft?
I know Microsoft acquired Activision.
My 'Lost Treasures of Infocom" box says (c)1991 Activision on it.
I have been experimenting with the "Stable Diffusion" API,
I think these Infocom games are the perfect fit for using it.
Last year I modified another Z-Machine Github and Implemented Text to Speech and Speech to Text in it.
My personal implementation had trouble understanding what I said accurately...
Perhaps Microsoft could do a better job.
I would like to see these Infocom games re-released with a Text to Image thing going on.
It would be neat to play with different images of what's going on in the game.
Stable Diffusion IMHO is too slow, but if they were prerendered and randomly selected / regularly updated.
I also think an AI could be used to extend the original games with new story branches and responses.
Something like GPT-3.
Do you have plans on implementing any of these features? 
If not, would you mind if I forked and gave it a go?
Would Microsoft mind?
I really think Microsoft should re-release these old games with the above-mentioned enhancements, and you should probably be the lead for the job!
If they just aren't interested tho, I am reasonably skilled at enhancing other people's GitHub projects. It's what I do, add super cool new features to old game engines.
I made all the SCI Sierra games load HighDef replacement graphics and play video cutscenes, and use truetype fonts but abandoned the project when Microsoft acquired Activision. I have a few things to say about updating those old games as well, (They are 256 color palette. Issues became complicated when the games used 'Palette Cycling").
I am not the greatest programmer, I am really good at modifying existing code bases,
I will be eagerly awaiting your reply, but please take your time and make it a good read :)
Thanks!
     - Myles

**Comment by BrianPeek** [comment]
Hi Myles,

Microsoft has not yet acquired Activision, so licensing of these titles is still in the hands of Activision.  That said, feel free to fork the repo and see what you come up with.  I have no further plans with this library at present...

Thanks,
Brian
